/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "../ui/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f3ff",
        "surface-container-high": "#e1e8fd",
        "surface-container-highest": "#dce2f7",
        "surface-container": "#e9edff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d3daef",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#dce2f7",
        "surface-tint": "#1f6c3a",
        "surface": "#f9f9ff",
        "background": "#f9f9ff",
        "primary": "#004c22",
        "primary-container": "#166534",
        "primary-fixed": "#a6f4b5",
        "primary-fixed-dim": "#8bd79b",
        "on-primary": "#ffffff",
        "on-primary-container": "#93e0a2",
        "on-primary-fixed": "#00210b",
        "on-primary-fixed-variant": "#005226",
        "inverse-primary": "#8bd79b",
        "secondary": "#2d6a48",
        "secondary-container": "#b0f1c7",
        "secondary-fixed": "#b0f1c7",
        "secondary-fixed-dim": "#95d4ac",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#33704e",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#0f5132",
        "tertiary": "#004b1f",
        "tertiary-container": "#00662d",
        "tertiary-fixed": "#95f8a7",
        "tertiary-fixed-dim": "#79db8d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#81e394",
        "on-tertiary-fixed": "#00210a",
        "on-tertiary-fixed-variant": "#005323",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface": "#141b2b",
        "on-surface-variant": "#404940",
        "on-background": "#141b2b",
        "outline": "#707a6f",
        "outline-variant": "#bfc9bd",
        "inverse-surface": "#293040",
        "inverse-on-surface": "#edf0ff",
      },
      spacing: {
        "space-xl": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "space-lg": "1rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2rem",
        "gutter": "1rem",
        "margin": "1rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontSize: {
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "metric-display": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
